# Generated by Django 2.2 on 2021-06-21 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_auto_20190424_0140'),
        ('text', '0010_auto_20210420_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstTimeCorrect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', models.IntegerField(default=0)),
                ('total_answers', models.IntegerField(default=0)),
                ('end_dt', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='user.Student')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_text', to='text.Text')),
            ],
        ),
    ]
