# Generated by Django 2.2 on 2020-12-18 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('text', '0005_auto_20201204_0136'),
        ('user', '0004_auto_20190424_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstTimeCorrect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_correct', models.IntegerField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_id', to='user.Student')),
                ('text_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_id', to='text.Text')),
            ],
        ),
    ]
