# Generated by Django 2.2 on 2020-12-18 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_time_correct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firsttimecorrect',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='user.Student'),
        ),
        migrations.AlterField(
            model_name='firsttimecorrect',
            name='text_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_text', to='text.Text'),
        ),
    ]
