# Generated by Django 2.2 on 2021-01-13 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_time_correct', '0002_auto_20201218_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firsttimecorrect',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='firsttimecorrect',
            old_name='text_id',
            new_name='text',
        ),
    ]
