# Generated by Django 2.2 on 2021-06-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_time_correct', '0003_auto_20210113_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='firsttimecorrect',
            name='end_dt',
            field=models.DateTimeField(null=True),
        ),
    ]
