# Generated by Django 2.2 on 2021-06-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_time_correct', '0004_firsttimecorrect_end_dt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firsttimecorrect',
            old_name='num_correct',
            new_name='correct_answers',
        ),
        migrations.AlterField(
            model_name='firsttimecorrect',
            name='end_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='firsttimecorrect',
            name='total_answers',
            field=models.IntegerField(default=0),
        )
    ]
