# Generated by Django 2.2 on 2021-06-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_time_correct', '0004_firsttimecorrect_end_dt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firsttimecorrect',
            name='num_correct',
        ),
        migrations.AddField(
            model_name='firsttimecorrect',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='firsttimecorrect',
            name='total_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='firsttimecorrect',
            name='end_dt',
            field=models.DateTimeField(),
        ),
    ]
