# Generated by Django 2.2 on 2021-06-10 22:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_time_correct', '0005_auto_20210610_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firsttimecorrect',
            name='end_dt',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 10, 22, 0, 58, 734235, tzinfo=utc)),
        ),
    ]
