# Generated by Django 2.2 on 2021-06-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_time_correct', '0006_auto_20210610_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firsttimecorrect',
            name='end_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
