version: "3.8"
services:
  django_backend:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: django_backend
    env_file:
      - secrets.env
    environment:
        # change depending on prod or dev server 
      - VIRTUAL_HOST=api.steps2ar.org
    expose:
      - "8000"

  node_frontend:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node_frontend
    environment:
      - VIRTUAL_HOST=steps2ar.org
    expose:
      - "80"
    depends_on:
      - django_backend

  nginx-proxy:
    container_name: nginx-proxy
    expose:
      - "1234"
      - "8000"
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
        # - "443:443"
    restart: "always"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - node_frontend
      - django_backend

  redis:
    container_name: redis
    expose:
      - "6379" 
    image: redis
    depends_on:
      - django_backend