FROM python:3

WORKDIR '/app'

RUN apt update \
    && apt upgrade \
    && git clone https://github.com/ereadingtool/ereadingtool.git \
    && cd ereadingtool \
    && git checkout upgrade/staging \
    && pip install -r requirements.txt

CMD ["python", "/app/ereadingtool/manage.py", "runserver", "0.0.0.0:8000"]

EXPOSE 8000
