version: "3.8"
services:
  django_backend:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: django_backend
    env_file:
      - secrets.env
    environment:
      - VIRTUAL_HOST=api.steps2ar.org
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=api.steps2ar.org
      - FRONTEND_HOST=steps2ar.org
      - REDIS_ENDPOINT=redis
    expose:
      - "8000"
      - "6379"
    restart: always
    volumes:
      - ./db.sqlite3:/app/ereadingtool/db.sqlite3
  
  admin_panel:
    build:
      context: .
      dockerfile: Dockerfile.admin_panel
    container_name: admin_panel
    env_file:
      - secrets.env
    environment:
      - VIRTUAL_HOST=admin.steps2ar.org
      - VIRTUAL_PORT=8001
      - LETSENCRYPT_HOST=admin.steps2ar.org
    expose:
      - "8001"
    restart: always
    volumes:
      - ./db.sqlite3:/app/ereadingtool/db.sqlite3

  node_frontend:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node_frontend
    environment:
      - VIRTUAL_HOST=steps2ar.org
      - LETSENCRYPT_HOST=steps2ar.org
    expose:
      - "80"
    depends_on:
      - django_backend
    restart: always

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    expose:
      - "1234"
      - "8000"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - ${PWD}/cors.conf:/etc/nginx/vhost.d/api.steps2ar.org
    depends_on:
      - django_backend
      - node_frontend
    restart: always

  docker-gen:
    image: jwilder/docker-gen
    container_name: docker-gen
    command: ["/usr/local/bin/docker-gen -notify-sighup nginx-proxy -watch -wait 30s:60s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"]
    entrypoint: /bin/sh -c
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always 

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx_proxy_le
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - NGINX_DOCKER_GEN_CONTAINER=docker-gen
      - DEFAULT_EMAIL=ereader@pdx.edu
      # Turn on for testing
      #- ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory
    restart: always
    depends_on:
      - nginx-proxy

  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - "6379"
    depends_on:
      - django_backend
    restart: always

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
