FROM python:3
  
WORKDIR '/app'

RUN apt update -y \
    && apt upgrade -y \
    && apt install wktohtmlpdf \
    && mkdir logs \
    && touch logs/access.log \
    && touch logs/error.log \
    && git clone https://github.com/ereadingtool/ereadingtool.git \
    && cd ereadingtool \
    && git checkout upgrade/staging \
    && pip install -r requirements.txt

COPY ./db.sqlite3 /app/ereadingtool/

CMD ["python", "/app/ereadingtool/manage.py", "runserver", "0.0.0.0:8000"]

EXPOSE 8000