# Generated by Django 2.1.5 on 2019-03-06 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now=True)),
                ('write_locked', models.BooleanField(default=False)),
                ('introduction', models.CharField(max_length=512)),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('conclusion', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextDifficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Text Difficulties',
            },
        ),
        migrations.CreateModel(
            name='TextGroupWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TextPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(blank=True, max_length=32, null=True)),
                ('tense', models.CharField(blank=True, max_length=32, null=True)),
                ('aspect', models.CharField(blank=True, max_length=32, null=True)),
                ('form', models.CharField(blank=True, max_length=32, null=True)),
                ('mood', models.CharField(blank=True, max_length=32, null=True)),
                ('instance', models.IntegerField(default=0)),
                ('phrase', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TextPhraseTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField()),
                ('correct_for_context', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TextSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField()),
                ('body', models.TextField()),
                ('text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='text.Text')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextWord',
            fields=[
                ('textphrase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='text.TextPhrase')),
            ],
            options={
                'abstract': False,
            },
            bases=('text.textphrase',),
        ),
        migrations.CreateModel(
            name='TextWordGroup',
            fields=[
                ('textphrase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='text.TextPhrase')),
            ],
            options={
                'abstract': False,
            },
            bases=('text.textphrase',),
        ),
        migrations.AddField(
            model_name='textphrasetranslation',
            name='text_phrase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='text.TextPhrase'),
        ),
        migrations.AddField(
            model_name='textphrase',
            name='text_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translated_words', to='text.TextSection'),
        ),
    ]
