# Generated by Django 2.1.5 on 2019-03-08 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0002_auto_20190306_0140'),
    ]

    operations = [
        migrations.RunSQL(
          ['DELETE FROM text_textsection where text_id is null']
        ),
        migrations.AlterField(
            model_name='textsection',
            name='text',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='text.Text'),
        ),
    ]
