# Generated by Django 2.1.5 on 2019-03-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_flashcards_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcards',
            name='words',
            field=models.ManyToManyField(related_name='flashcards', to='text.TextPhrase'),
        ),
    ]
