# Generated by Django 2.1.5 on 2019-03-14 23:56

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('user', '0002_auto_20190313_2251'),
        ('text', '0003_auto_20190308_0130'),
        ('flashcards', '0003_auto_20190308_0147'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flashcards',
            new_name='StudentFlashcards',
        ),
        migrations.RenameField(
            model_name='studentflashcards',
            old_name='words',
            new_name='phrases',
        ),
    ]
