# Generated by Django 2.1.5 on 2019-03-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_auto_20190316_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentflashcardsession',
            name='mode',
            field=models.CharField(choices=[('review', 'Review'), ('review_and_answer', 'Review and Answer')], default='review', max_length=32),
        ),
        migrations.AddField(
            model_name='studentflashcardsession',
            name='state',
            field=models.CharField(default='mode_choice', max_length=64),
        ),
    ]
