# Generated by Django 2.1.5 on 2019-03-20 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_auto_20190319_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentflashcardsession',
            name='current_flashcard',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='session', to='flashcards.StudentFlashcard'),
        ),
        migrations.AlterField(
            model_name='studentflashcardsession',
            name='mode',
            field=models.CharField(choices=[('review', 'Review Only Mode.  This mode allows you to review your flashcards without submitting answers.'), ('review_and_answer', '\n      Review and Answer Mode.  This mode requires you to answer each flashcard as well as self-assess your performance.\n      ')], default='review', max_length=32),
        ),
    ]
