# Generated by Django 2.1.5 on 2019-03-25 22:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0008_auto_20190320_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentflashcard',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentflashcardsession',
            name='mode',
            field=models.CharField(choices=[('review', 'Review Only Mode.  This mode allows you to review your flashcards without submitting answers.'), ('review_and_answer', 'Review and Answer Mode.  This mode requires you to answer each flashcard as well as \n    self-assess your performance.')], default='review', max_length=32),
        ),
    ]
