# Generated by Django 2.1.5 on 2019-03-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0009_auto_20190325_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentflashcard',
            name='next_review_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='studentflashcard',
            name='easiness',
            field=models.FloatField(default=2.5),
        ),
        migrations.AlterField(
            model_name='studentflashcard',
            name='interval',
            field=models.FloatField(default=1),
        ),
    ]
