# Generated by Django 2.1.7 on 2019-04-12 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0003_auto_20190308_0130'),
        ('user', '0003_remove_student_flashcards'),
        ('flashcards', '0010_auto_20190329_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorFlashcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('next_review_dt', models.DateTimeField(null=True)),
                ('repetitions', models.IntegerField(default=0)),
                ('interval', models.FloatField(default=1)),
                ('easiness', models.FloatField(default=2.5)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='user.Instructor')),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_flashcards', to='text.TextPhrase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='studentflashcard',
            name='phrase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_flashcards', to='text.TextPhrase'),
        ),
    ]
