# Generated by Django 2.2 on 2019-05-13 23:39

from django.db import migrations, models
import flashcards.student.session.models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0013_auto_20190513_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentflashcardsession',
            name='current_flashcard',
            field=models.OneToOneField(blank=True, null=True, on_delete=flashcards.student.session.models.SET_NULL_OR_CASCADE, related_name='session', to='flashcards.StudentFlashcard'),
        ),
    ]
