# Generated by Django 2.0.6 on 2018-06-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now=True)),
                ('write_locked', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('introduction', models.CharField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
