# Generated by Django 2.0.5 on 2018-05-26 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_student_difficulty_preference'),
        ('quiz', '0002_auto_20180523_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_quiz', to='user.Instructor'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='write_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='write_locker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editing', to='user.Instructor'),
        ),
    ]
