# Generated by Django 2.0.6 on 2018-06-06 20:54

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20180605_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='introduction',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
