# Generated by Django 2.1 on 2018-10-02 03:12

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL("""
    CREATE VIEW report_student_performance AS SELECT
        rowid as id,
        student_id,
        text_id,
        text_reading_id,
        text_section_id,
        start_dt,
        end_dt,
        text_difficulty_slug,
        CAST(SUM(student_answers.correct) AS FLOAT) as answered_correctly,
        CAST(COUNT(DISTINCT question_id) AS FLOAT) as attempted_questions
    FROM
        (SELECT
            text_readings.student_id as student_id,
            text_reading_id,
            text_section_id,
            texts.id as text_id,
            text_readings_answers.question_id,
            answers.correct as correct,
            text_readings_answers.created_dt,
            text_readings.start_dt start_dt,
            text_readings.end_dt end_dt,
            text_difficulty.slug as text_difficulty_slug
            
        FROM text_reading_studenttextreadinganswers as text_readings_answers
        
        LEFT JOIN text_reading_studenttextreading text_readings
        on text_readings_answers.text_reading_id = text_readings.id
        
        LEFT JOIN question_answer as answers
        on answers.id  = text_readings_answers.answer_id
        
        LEFT JOIN text_text as texts
        on texts.id = text_readings.text_id
        
        LEFT JOIN text_textdifficulty text_difficulty
        on texts.difficulty_id = text_difficulty.id
        
        WHERE text_readings.state = 'complete'
        
        GROUP BY text_reading_id, text_section_id, answers.question_id
        ORDER BY text_readings_answers.created_dt) as student_answers
    
    GROUP BY text_reading_id, text_section_id;
        """)
    ]



