# Generated by Django 2.2 on 2020-11-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPerformance',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
                ('text_difficulty_slug', models.SlugField()),
                ('answered_correctly', models.IntegerField()),
                ('attempted_questions', models.IntegerField()),
            ],
            options={
                'db_table': 'report_student_performance',
                'managed': False,
            },
        ),
    ]
