# Generated by Django 2.2 on 2021-03-26 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('text', '0006_textsection_translation_service_processed'),
        ('user', '0004_auto_20190424_0140'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFirstTimeCorrect',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('num_correct', models.IntegerField()),
                ('num_questions', models.IntegerField()),
                ('text_difficulty_slug', models.SlugField()),
            ],
            options={
                'db_table': 'report_first_time_correct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentReadingsComplete',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
                ('text_difficulty_slug', models.SlugField()),
            ],
            options={
                'db_table': 'report_texts_complete',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentReadingsInProgress',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('start_dt', models.DateTimeField()),
                ('text_difficulty_slug', models.SlugField()),
            ],
            options={
                'db_table': 'report_texts_in_progress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Flashcards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.IntegerField(null=True)),
                ('phrase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='text.TextPhrase')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_student_flashcards', to='user.Student')),
                ('text_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='text.TextSection')),
            ],
            options={
                'unique_together': {('student', 'instance', 'phrase', 'text_section')},
            },
        ),
    ]
