# Generated by Django 2.2 on 2021-01-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFirstTimeCorrect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_correct', models.IntegerField()),
                ('num_questions', models.IntegerField()),
                ('text_difficulty_slug', models.SlugField()),
            ],
            options={
                'db_table': 'report_first_time_correct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentReadingsComplete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
                ('text_difficulty_slug', models.SlugField()),
            ],
            options={
                'db_table': 'report_texts_complete',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentReadingsInProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dt', models.DateTimeField()),
                ('text_difficulty_slug', models.SlugField()),
            ],
            options={
                'db_table': 'report_texts_in_progress',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='StudentPerformance',
        ),
    ]
