# Generated by Django 2.2 on 2021-01-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20210129_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcards',
            name='instance',
            field=models.IntegerField(null=True),
        ),
    ]
