# Generated by Django 2.0.6 on 2018-07-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20180608_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='feedback',
            field=models.CharField(max_length=2048),
        ),
    ]
