# Generated by Django 2.0.6 on 2018-07-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20180702_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=2048),
        ),
    ]
