# Generated by Django 2.1 on 2018-08-23 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0002_auto_20180709_2128'),
        ('user', '0001_initial'),
        ('text', '0003_text_conclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='intro', max_length=64)),
                ('currently_reading', models.NullBooleanField()),
                ('start_dt', models.DateTimeField(auto_now_add=True)),
                ('end_dt', models.DateTimeField(null=True)),
                ('current_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_readings', to='text.TextSection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Student')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Text')),
            ],
        ),
        migrations.CreateModel(
            name='TextReadingAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_reading_answers', to='question.Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_reading_answers', to='question.Question')),
                ('text_reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_reading_answers', to='text_reading.TextReading')),
                ('text_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_reading_answers', to='text.TextSection')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='textreadinganswers',
            unique_together={('text_reading', 'text_section', 'question', 'answer')},
        ),
    ]
