# Generated by Django 2.0.7 on 2018-08-10 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('text', '0002_auto_20180709_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='intro', max_length=64)),
                ('currently_reading', models.NullBooleanField()),
                ('start_dt', models.DateTimeField(auto_now_add=True)),
                ('end_dt', models.DateTimeField(null=True)),
                ('current_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='text.TextSection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Student')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Text')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='textreading',
            unique_together={('student', 'text')},
        ),
    ]
