# Generated by Django 2.1.5 on 2019-03-06 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0002_auto_20190306_0140'),
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorTextReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='intro', max_length=64)),
                ('currently_reading', models.NullBooleanField()),
                ('start_dt', models.DateTimeField(auto_now_add=True)),
                ('end_dt', models.DateTimeField(null=True)),
                ('last_read_dt', models.DateTimeField(null=True)),
                ('random_seed', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstructorTextReadingAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentTextReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='intro', max_length=64)),
                ('currently_reading', models.NullBooleanField()),
                ('start_dt', models.DateTimeField(auto_now_add=True)),
                ('end_dt', models.DateTimeField(null=True)),
                ('last_read_dt', models.DateTimeField(null=True)),
                ('random_seed', models.CharField(max_length=256)),
                ('current_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='text.TextSection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentTextReadingAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question')),
                ('text_reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_reading_answers', to='text_reading.StudentTextReading')),
                ('text_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.TextSection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
