# Generated by Django 2.1 on 2018-08-15 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20180709_2128'),
        ('text', '0003_text_conclusion'),
        ('text_reading', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='textsectionreading',
            unique_together={('text_reading', 'text_section', 'question')},
        ),
    ]
