# Generated by Django 2.1 on 2018-08-23 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text_reading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textreading',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_readings', to='user.Student'),
        ),
    ]
