# Generated by Django 2.1.2 on 2018-12-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_reading', '0002_auto_20181108_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructortextreading',
            name='last_read_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='studenttextreading',
            name='last_read_dt',
            field=models.DateTimeField(null=True),
        ),
    ]
