# Generated by Django 2.1 on 2018-09-21 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('question', '0002_auto_20180709_2128'),
        ('text', '0003_text_conclusion'),
        ('text_reading', '0002_auto_20180823_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorTextReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='intro', max_length=64)),
                ('currently_reading', models.NullBooleanField()),
                ('start_dt', models.DateTimeField(auto_now_add=True)),
                ('end_dt', models.DateTimeField(null=True)),
                ('current_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='text.TextSection')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_readings', to='user.Instructor')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Text')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstructorTextReadingAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question')),
                ('text_reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_reading_answers', to='text_reading.InstructorTextReading')),
                ('text_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.TextSection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentTextReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='intro', max_length=64)),
                ('currently_reading', models.NullBooleanField()),
                ('start_dt', models.DateTimeField(auto_now_add=True)),
                ('end_dt', models.DateTimeField(null=True)),
                ('current_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='text.TextSection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_readings', to='user.Student')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Text')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentTextReadingAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question')),
                ('text_reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_reading_answers', to='text_reading.StudentTextReading')),
                ('text_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.TextSection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='textreading',
            name='current_section',
        ),
        migrations.RemoveField(
            model_name='textreading',
            name='student',
        ),
        migrations.RemoveField(
            model_name='textreading',
            name='text',
        ),
        migrations.AlterUniqueTogether(
            name='textreadinganswers',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='textreadinganswers',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='textreadinganswers',
            name='question',
        ),
        migrations.RemoveField(
            model_name='textreadinganswers',
            name='text_reading',
        ),
        migrations.RemoveField(
            model_name='textreadinganswers',
            name='text_section',
        ),
        migrations.DeleteModel(
            name='TextReading',
        ),
        migrations.DeleteModel(
            name='TextReadingAnswers',
        ),
        migrations.AlterUniqueTogether(
            name='studenttextreadinganswers',
            unique_together={('text_reading', 'text_section', 'question', 'answer')},
        ),
        migrations.AlterUniqueTogether(
            name='instructortextreadinganswers',
            unique_together={('text_reading', 'text_section', 'question', 'answer')},
        ),
    ]
