# Generated by Django 2.1.2 on 2019-01-11 00:23
import os

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_reading', '0003_auto_20181228_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructortextreading',
            name='random_seed',
            field=models.CharField(default=os.urandom(256), max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studenttextreading',
            name='random_seed',
            field=models.CharField(default=os.urandom(256), max_length=256),
            preserve_default=False,
        ),
    ]
