# Generated by Django 2.1.2 on 2018-10-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('text', '0012_textword_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.ManyToManyField(related_name='flashcards', to='text.TextWord')),
            ],
        ),
    ]
