# Generated by Django 2.1.2 on 2018-11-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flashcards', '0001_initial'),
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcards',
            name='words',
            field=models.ManyToManyField(related_name='flashcards', to='text.TextWord'),
        ),
    ]
