# Generated by Django 2.2 on 2019-04-29 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0011_auto_20190412_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentflashcardsession',
            name='current_flashcard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='flashcard_sessions', to='flashcards.StudentFlashcard'),
        ),
        migrations.AlterField(
            model_name='studentflashcardsession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_sessions', to='user.Student'),
        ),
    ]
