# Generated by Django 2.0.3 on 2018-03-16 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textdifficulty',
            options={'verbose_name_plural': 'Text Difficulties'},
        ),
    ]
