# Generated by Django 2.1.2 on 2018-11-08 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('tag', '0001_initial'),
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_texts', to='user.Instructor'),
        ),
        migrations.AddField(
            model_name='text',
            name='difficulty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='texts', to='text.TextDifficulty'),
        ),
        migrations.AddField(
            model_name='text',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_text', to='user.Instructor'),
        ),
        migrations.AddField(
            model_name='text',
            name='tags',
            field=models.ManyToManyField(related_name='texts', to='tag.Tag'),
        ),
        migrations.AddField(
            model_name='text',
            name='write_locker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editing', to='user.Instructor'),
        ),
        migrations.AlterUniqueTogether(
            name='textword',
            unique_together={('instance', 'word', 'text_section')},
        ),
    ]
