# Generated by Django 2.1.5 on 2019-03-06 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('text', '0001_initial'),
        ('tag', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_texts', to='user.Instructor'),
        ),
        migrations.AddField(
            model_name='text',
            name='difficulty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='texts', to='text.TextDifficulty'),
        ),
        migrations.AddField(
            model_name='text',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_text', to='user.Instructor'),
        ),
        migrations.AddField(
            model_name='text',
            name='tags',
            field=models.ManyToManyField(related_name='texts', to='tag.Tag'),
        ),
        migrations.AddField(
            model_name='text',
            name='write_locker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editing', to='user.Instructor'),
        ),
#        migrations.AlterUniqueTogether(
#            name='textphrase',
#            unique_together={('instance', 'phrase', 'text_section')},
#        ),
        migrations.AddField(
            model_name='textgroupword',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='text.TextWordGroup'),
        ),
        migrations.AddField(
            model_name='textgroupword',
            name='word',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_word', to='text.TextWord'),
        ),
        migrations.AlterUniqueTogether(
            name='textgroupword',
            unique_together={('group', 'word', 'order')},
        ),
    ]
