# Generated by Django 2.0.5 on 2018-05-18 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0002_text_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='texts', to='quiz.Quiz'),
        ),
    ]
