# Generated by Django 2.1 on 2018-08-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0002_auto_20180709_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='conclusion',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
