# Generated by Django 2.2 on 2020-11-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0003_auto_20190308_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='textphrase',
            name='lemma',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='textphrase',
            unique_together={('instance', 'phrase', 'text_section', 'lemma')},
        ),
    ]
