# Generated by Django 2.1.2 on 2018-10-11 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0003_text_conclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextDefinitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TextWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_form', models.CharField(max_length=128)),
                ('definitions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='text.TextDefinitions')),
            ],
        ),
        migrations.CreateModel(
            name='TextWordMeaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(max_length=32)),
                ('text', models.TextField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='text.TextWord')),
            ],
        ),
        migrations.AddField(
            model_name='text',
            name='definitions',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text', to='text.TextDefinitions'),
        ),
    ]
