# Generated by Django 2.0.5 on 2018-05-26 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0003_auto_20180518_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='quiz.Quiz'),
            preserve_default=False,
        ),
    ]
