# Generated by Django 2.1.2 on 2019-01-12 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0003_auto_20190110_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textgroupword',
            name='word',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_word', to='text.TextWord'),
        ),
    ]
