# Generated by Django 2.1.2 on 2018-10-11 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0004_auto_20181011_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='definitions',
        ),
        migrations.AddField(
            model_name='textsection',
            name='definitions',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text', to='text.TextDefinitions'),
        ),
    ]
