# Generated by Django 2.2 on 2020-12-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0004_auto_20201113_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textphrase',
            name='lemma',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
