# Generated by Django 2.1.5 on 2019-02-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0004_auto_20190112_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='textwordgroup',
            name='instance',
            field=models.IntegerField(default=0),
        ),
    ]
