# Generated by Django 2.2 on 2021-01-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0005_auto_20201204_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsection',
            name='translation_service_processed',
            field=models.IntegerField(default=0),
        ),
    ]
