# Generated by Django 2.1.5 on 2019-02-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0005_textwordgroup_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='textwordgroup',
            name='aspect',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='textwordgroup',
            name='form',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='textwordgroup',
            name='mood',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='textwordgroup',
            name='pos',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='textwordgroup',
            name='tense',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
