# Generated by Django 2.1.2 on 2018-10-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0005_auto_20181011_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='textwordmeaning',
            name='aspect',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='textwordmeaning',
            name='form',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='textwordmeaning',
            name='mood',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='textwordmeaning',
            name='tense',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='textwordmeaning',
            name='pos',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
