# Generated by Django 2.1.2 on 2018-10-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0006_auto_20181012_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textwordmeaning',
            name='aspect',
        ),
        migrations.RemoveField(
            model_name='textwordmeaning',
            name='form',
        ),
        migrations.RemoveField(
            model_name='textwordmeaning',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='textwordmeaning',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='textwordmeaning',
            name='tense',
        ),
        migrations.AddField(
            model_name='textword',
            name='aspect',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='textword',
            name='form',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='textword',
            name='mood',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='textword',
            name='pos',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='textword',
            name='tense',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
