# Generated by Django 2.1.2 on 2018-10-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0007_auto_20181012_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textword',
            name='aspect',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='textword',
            name='form',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='textword',
            name='mood',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='textword',
            name='pos',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='textword',
            name='tense',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
