# Generated by Django 2.2 on 2021-04-07 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190424_0140'),
        ('text', '0007_text_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_ratings', to='user.Student')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='text.Text')),
            ],
            options={
                'verbose_name_plural': 'Text Ratings',
            },
        ),
    ]
