# Generated by Django 2.2 on 2021-04-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190424_0140'),
        ('text', '0008_textrating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='textrating',
            unique_together={('student', 'text', 'rating')},
        ),
    ]
