# Generated by Django 2.1.2 on 2018-10-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0008_auto_20181012_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='conclusion',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
