# Generated by Django 2.1.2 on 2018-10-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0009_auto_20181012_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='textwordmeaning',
            name='correct_for_context',
            field=models.BooleanField(default=False),
        ),
    ]
