# Generated by Django 2.1.2 on 2018-10-18 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0010_textwordmeaning_correct_for_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textsection',
            name='definitions',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_section', to='text.TextDefinitions'),
        ),
    ]
