# Generated by Django 2.1.2 on 2018-10-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0011_auto_20181018_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='textword',
            name='frequency',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
