# Generated by Django 2.1.2 on 2018-10-26 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0014_auto_20181025_2306'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='textword',
            unique_together={('instance', 'word', 'definitions')},
        ),
    ]
