# Generated by Django 2.1.2 on 2018-10-29 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0015_auto_20181026_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textsection',
            name='definitions',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text_section', to='text.TextDefinitions'),
        ),
    ]
