# Generated by Django 2.1.2 on 2018-11-06 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0016_auto_20181029_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextWordTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_for_context', models.BooleanField(default=False)),
                ('phrase', models.TextField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='text.TextWord')),
            ],
        ),
        migrations.RemoveField(
            model_name='textwordmeaning',
            name='word',
        ),
        migrations.DeleteModel(
            name='TextWordMeaning',
        ),
    ]
