# Generated by Django 2.1.2 on 2018-11-07 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0017_auto_20181106_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textsection',
            name='definitions',
        ),
        migrations.AlterUniqueTogether(
            name='textword',
            unique_together={('instance', 'word')},
        ),
    ]
