# Generated by Django 2.1.2 on 2018-11-07 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0019_auto_20181107_0301'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextDefinitions',
        ),
        migrations.AddField(
            model_name='textword',
            name='text',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='text.Text'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='textword',
            unique_together={('instance', 'word', 'text')},
        ),
    ]
