# Generated by Django 2.1.2 on 2018-11-07 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0020_auto_20181107_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textword',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translated_words', to='text.Text'),
        ),
    ]
