# Generated by Django 2.1.2 on 2018-11-07 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0021_auto_20181107_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='textword',
            name='text_section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='translated_words', to='text.TextSection'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='textword',
            unique_together={('instance', 'word', 'text_section')},
        ),
    ]
