# Generated by Django 2.1.2 on 2018-11-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0022_auto_20181107_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textword',
            name='text',
        ),
    ]
