# Generated by Django 2.1.5 on 2019-03-15 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190313_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='flashcards',
        ),
    ]
