# Generated by Django 2.1.7 on 2019-04-24 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_student_flashcards'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResearchConsent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StudentResearchConsentRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dt', models.DateTimeField(auto_now_add=True)),
                ('end_dt', models.DateTimeField(blank=True, null=True)),
                ('student_consent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_ranges', to='user.StudentResearchConsent')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='research_consent',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.StudentResearchConsent'),
        ),
    ]
