# Generated by Django 2.1.5 on 2019-03-06 01:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('key', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
