# Generated by Django 2.1.5 on 2019-01-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181206_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='admin',
            field=models.BooleanField(null=True),
        ),
    ]
