# Generated by Django 2.2 on 2021-05-13 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190424_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDashboardUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDashboardUserRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dt', models.DateTimeField(auto_now_add=True)),
                ('end_dt', models.DateTimeField(blank=True, null=True)),
                ('student_dashboard_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_connection_ranges', to='user.StudentDashboardUser')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='dashboard_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.StudentDashboardUser'),
        ),
    ]
