# Generated by Django 2.2 on 2021-05-14 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210513_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dashboard_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.StudentDashboardUser'),
        ),
    ]
