# Generated by Django 2.2 on 2021-05-14 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210514_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dashboard_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.StudentDashboardUser'),
        ),
    ]
